# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160410_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterparticle',
            name='id',
        ),
        migrations.AlterField(
            model_name='waterparticle',
            name='deviceID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='waterparticle',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
