# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160410_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterparticle',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waterparticle',
            name='deviceID',
            field=models.CharField(max_length=50),
        ),
    ]
