# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='deviceID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
