# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160410_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterparticle',
            name='token',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
