# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_waterparticle_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='access',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='mobileNo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='waterparticle',
            name='access',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='waterparticle',
            name='salinity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
