# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterparticle',
            name='orp',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='waterparticle',
            name='ph',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='waterparticle',
            name='salinity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='waterparticle',
            name='temperature',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
