# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160421_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='from_orp',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='from_ph',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='from_salinity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='from_temperature',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='to_orp',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='to_ph',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='to_salinity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='to_temperature',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
