# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160421_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterparticle',
            name='access',
            field=models.CharField(blank=True, default=b'public', max_length=20, null=True),
        ),
    ]
